"""Add solve_requests table

Revision ID: 698c31130684
Revises: 2a6a62db4169
Create Date: 2026-01-06 14:56:49.405549

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "698c31130684"
down_revision: Union[str, None] = "2a6a62db4169"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "solve_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("subject_filter", sa.String(length=255), nullable=True),
        sa.Column("matched_subject_id", sa.Integer(), nullable=True),
        sa.Column("matched_teacher_id", sa.Integer(), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column(
            "chunks_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("used_rag", sa.Boolean(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "ready",
                "error",
                name="solverequeststatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["matched_subject_id"],
            ["subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matched_teacher_id"],
            ["teachers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_solve_requests_matched_subject_id"),
        "solve_requests",
        ["matched_subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_solve_requests_matched_teacher_id"),
        "solve_requests",
        ["matched_teacher_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_solve_requests_status"), "solve_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_solve_requests_subject_filter"),
        "solve_requests",
        ["subject_filter"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_solve_requests_subject_filter"), table_name="solve_requests")
    op.drop_index(op.f("ix_solve_requests_status"), table_name="solve_requests")
    op.drop_index(
        op.f("ix_solve_requests_matched_teacher_id"), table_name="solve_requests"
    )
    op.drop_index(
        op.f("ix_solve_requests_matched_subject_id"), table_name="solve_requests"
    )
    op.drop_table("solve_requests")
    # ### end Alembic commands ###
